// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:travel_memories/features/countries/data/models/country_details_model.dart';
import 'package:travel_memories/features/memories/data/models/memory_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CountryDetailsModelAdapter());
    registerAdapter(MemoryModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CountryDetailsModelAdapter());
    registerAdapter(MemoryModelAdapter());
  }
}
